---
door_1:
  door_length: 1.2
door_2:
  door_length: 1.1
door_3:
  door_length: 1.0
door_4:
  door_length: 0.9
door_5:
  door_length: 1.3
door_6:
  door_length: 1.4
door_7:
  door_length: 1.2
door_8:
  door_length: 1.3
door_9:
  door_length: 1.4
door_10:
  door_length: 1.1
door_11:
  door_length: 1.0
door_12:
  door_length: 0.9
door_13:
  door_length: 1.4
door_14:
  door_length: 1.3
door_15:
  door_length: 1.2
door_16:
  door_length: 1.1
door_17:
  door_length: 1.0
door_18:
  door_length: 0.9
